apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  selector:
    app: minio-server
  ports:
    - name: minio-server-port
      port: 4100
      targetPort: 4100
    - name: minio-console-port
      port: 4200
      targetPort: 4200
      nodePort: 30420
  type: NodePort