apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq-server
  ports:
    - name: server-port
      port: 5672
      targetPort: 5672
    - name: console-port
      port: 15672
      targetPort: 15672
      nodePort: 30567
  type: NodePort