apiVersion: v1
kind: ConfigMap
metadata:
  name: user-configmap
data:
  PORT: "3000"
  DB_URL: mongodb://host.docker.internal:27017/crowdspace-user
  RABBITMQ_ENDPOINT: amqp://rabbitmq-service:5672
  REDIS_URL: redis://redis-service:6379
  ISSUER: crowdspace.in
  AUDIENCE: crowdspace.in
  FRONTEND_URL: http://localhost:5173