apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-deployment
  labels:
    app: chat-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-svc
  template:
    metadata:
      labels:
        app: chat-svc
    spec:
      containers:
        - name: chat-svc-container
          image: crowdspace-chat:dev-latest
          imagePullPolicy : IfNotPresent
          ports:
            - containerPort: 7070
          envFrom:
            - configMapRef:
                name: chat-configmap