apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-svc
  template:
    metadata:
      labels:
        app: user-svc
    spec:
      containers:
        - name: user-container
          image: crowdspace-user:dev-latest
          imagePullPolicy : IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: user-secret
            - configMapRef:
                name: user-configmap
          command:
            - node
            - --trace-deprecation
            - dist/index.js